### ISSUE TITLE
App won't display more than three related content types with Saudi schema

### ISSUE THREAD

**Issue by ddohler** [WorldBank-Transport/DRIVER-Android#46]
In #45 , we thought that manually removing URI-encoded characters at the start of the `Person` related content type name caused the related content type to reappear. However, we later realized that its reappearance came at the expense of the `Photograph` section, which was no longer available (and whose camelCased label contained no special characters).

There were some issues with the `Photograph` schema due to earlier bugs, so we fixed those and tried again, but the `Photograph` section still didn't appear.

Next, we added a new related content type, called `Photo`, to the schema. At this point, the `Person` content type disappeared and the newly-added `Photo` type took its place. Deleting the new `Photos` section caused the `Person` section to reappear.

Here's a chronology of the changes we made and the content types that were showing up:
Initial: `Details`, `Vehicle`, `Photo` (missing `Person`)
Removed URI encoding in `Person` label: `Details`, `Vehicle`, `Person` (missing `Photograph`)
Fixed incorrect `title` field in `Photograph`: `Details`, `Vehicle`, `Person`
Added new `Photo` type: `Details`, `Vehicle`, `Photo` (missing `Photograph`, `Person`)
Removed `Photo` type: `Details`, `Vehicle`, `Person` (missing `Photograph`)

We watched the log for the gradle task, and it does generate class files for all of the parts of the schema.

**Comment by flibbertigibbet** [comment]
This is due to WorldBank-Transport/DRIVER#573
